name: PR to Main

on:
  pull_request:
    branches:
      - main

jobs:
  ####################### Lint and Test ########################################
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
          registry-url: https://npm.pkg.github.com
          scope: "@obfns"

      - name: npm install and type-check
        run: |
          npm ci
          npm run type-check

      - name: lint
        run: npm run lint

      - name: Comment with Test Coverage
        uses: dkershner6/jest-coverage-commenter-action@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          test_command: "npm run test:coverage"